import { createHmac } from "node:crypto";
import { test, expect } from "@playwright/test";

test("Pinterest description draft, approval, persistence and mobile layout", async ({ page, context }, testInfo) => {
  const payload = Buffer.from(JSON.stringify({ userId: "browser-test-owner", email: "owner@test.invalid", expiresAt: Math.floor(Date.now() / 1000) + 3600 })).toString("base64url");
  const signature = createHmac("sha256", "pinterest-description-browser-test-only").update(payload).digest("base64url");
  await context.addCookies([{ name: "etsy_pinterest_admin", value: `${payload}.${signature}`, url: "http://127.0.0.1:3107" }]);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let saves = 0;
  let navigationCount = 0;
  page.on("request", request => { if (request.method() === "PATCH") saves++; });
  page.on("framenavigated", () => navigationCount++);
  await page.goto("/pinterest/queue");
  await expect(page.getByText("AI", { exact: true })).toBeVisible();
  const edit = page.getByRole("button", { name: "Edit Pinterest description", exact: true });
  await expect(edit).toBeVisible();
  await edit.click();
  const dialog = page.getByRole("dialog");
  const textarea = dialog.getByLabel("Description", { exact: true });
  await expect(textarea).toBeFocused();
  const original = await textarea.inputValue();
  const baselineNavigations = navigationCount;
  await dialog.getByRole("button", { name: "Update With AI" }).click();
  await expect(dialog.getByRole("button", { name: "Generating..." })).toBeDisabled();
  await expect(dialog.getByRole("status")).toHaveText("AI draft ready. Not saved.");
  await expect(dialog).toBeVisible();
  await expect(textarea).toHaveValue(/A bookish twist on Halloween/);
  expect(saves).toBe(0);
  expect(navigationCount).toBe(baselineNavigations);
  await expect.poll(() => dialog.locator("img").evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: testInfo.outputPath("desktop-description.png") });
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(edit).toBeFocused();
  await edit.click();
  await expect(textarea).toHaveValue(original);
  await dialog.getByRole("button", { name: "Update With AI" }).click();
  await expect(dialog.getByRole("status")).toHaveText("AI draft ready. Not saved.");
  const approved = "A spooky-season reading design for book lovers. My approved Pinterest description.";
  await textarea.fill(approved);
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".caption-snippet")).toHaveText(approved);
  await expect(page.getByText("AI", { exact: true })).toHaveCount(0);
  expect(saves).toBe(1);
  await page.reload();
  await expect(page.locator(".caption-snippet")).toHaveText(approved);

  await edit.click();
  await page.route("**/api/pinterest/queue/*/description", async route => {
    if (route.request().method() === "POST") await route.fulfill({ status: 502, json: { error: "AI test failure" } });
    else await route.continue();
  });
  await dialog.getByRole("button", { name: "Update With AI" }).click();
  await expect(dialog.getByRole("alert")).toHaveText("AI test failure");
  await expect(textarea).toHaveValue(approved);
  await page.unroute("**/api/pinterest/queue/*/description");
  await page.route("**/api/pinterest/queue/*/description", async route => {
    await route.fulfill({ status: 409, json: { error: "Publishing has started. Your draft was not saved." } });
  });
  await textarea.fill("Unsaved changed text.");
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("Publishing has started");
  await expect(textarea).toHaveValue("Unsaved changed text.");
  await page.unroute("**/api/pinterest/queue/*/description");
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);

  // Cancelling an in-flight generation must not leak its response into a reopened editor.
  await edit.click();
  await dialog.getByRole("button", { name: "Update With AI" }).click();
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await edit.click();
  await expect(textarea).toHaveValue(approved);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeInViewport();
  const box = await dialog.locator(".modal-content").boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: testInfo.outputPath("mobile-description.png") });
  await dialog.getByRole("button", { name: "Save", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(dialog.getByRole("button", { name: "Close", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  expect(errors).toEqual([]);
});
